name: Deploy DEV to QA - Azure SQL

on: workflow_dispatch

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/sql-action@v2.3
      with:        
        connection-string: ${{ secrets.QA_DB_CONNECTION_STRING }}
        path: './dev-db/dev-db-proj/dev-db-proj.sqlproj'
        action: 'publish'
        build-arguments: '-c Release'                 # Optional build options passed to dotnet build
        arguments: >
          /p:DropObjectsNotInSource=true 
          /p:ExcludeObjectTypes=Users;Permissions;RoleMembership
